### ISSUE TITLE
文档地址里面demo的code好像是错的

### ISSUE THREAD

**Issue by ArthurSuz** [ws456999/so-form#3]
https://ws456999.github.io/so-form/docs/usage/status.html
这个文档地址里面demo的code好像是错的
![image](https://user-images.githubusercontent.com/29251610/49512677-abd86280-f8c9-11e8-914d-a7c7df09d56f.png)

**Comment by ws456999** [comment]
got it, fixed now

**Comment by ws456999** [comment]
文档有缓存，迟一点才会生效

**Comment by ArthurSuz** [comment]
目前还没生效
![image](https://user-images.githubusercontent.com/29251610/49555732-d8c55d80-f93b-11e8-90a8-d9f8e4db8b5e.png)

**Comment by ArthurSuz** [comment]
这个目前还没有更新
